export const AREAS = [

    { id: "almacen", nombre: "Almacen" },
    { id: "control de calidad", nombre: "Control de Calidad" },
    { id: "comedor", nombre: "Comedor" },
    { id: "comite tecnico", nombre: "Comité Técnico" },
    { id: "contabilidad", nombre: "Contabilidad" },
    { id: "direccion", nombre: "Dirección General" },
    { id: "mantenimiento", nombre: "Mantenimiento" },
    { id: "gerente operaciones", nombre: "Gerencia de Operaciones" },
    { id: "gestion sostenible", nombre: "Gestión Sostenible" },
    { id: "produccion", nombre: "Producción" },
    { id: "recepcion", nombre: "Recepcion" },
    { id: "recursos humanos", nombre: "Recursos Humanos" },
    { id: "responsable sanitario", nombre: "Responsable Sanitario" },
    { id: "salud ocupacional", nombre: "Salud Ocupacional" },
    { id: "seguridad", nombre: "Seguridad" },
    { id: "servicios", nombre: "Servicios" },
    { id: "servicio medico", nombre: "Servicio Médico" },
    { id: "sistemas", nombre: "Sistemas" },
    { id: "validaciones", nombre: "Validaciones" },
    { id: "vigilancia", nombre: "Vigilancia" },
    { id: "compras", nombre: "Compras" },

];